### Recurrent Neural Network

In [1]:
import pandas as pd
data = pd.read_csv('RNN.csv')

In [2]:
data.head()

a     b     c     d    e     f     g     h     i     j     k     l  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

      m  type  
0  1065     1  
1  1050     1  
2  1185     1  
3  1480     1  
4   735     1

In [3]:
data.describe().transpose()

count        mean         std     min       25%      50%       75%  \
a     178.0   13.000618    0.811827   11.03   12.3625   13.050   13.6775   
b     178.0    2.336348    1.117146    0.74    1.6025    1.865    3.0825   
c     178.0    2.366517    0.274344    1.36    2.2100    2.360    2.5575   
d     178.0   19.494944    3.339564   10.60   17.2000   19.500   21.5000   
e     178.0   99.741573   14.282484   70.00   88.0000   98.000  107.0000   
f     178.0    2.295112    0.625851    0.98    1.7425    2.355    2.8000   
g     178.0    2.029270    0.998859    0.34    1.2050    2.135    2.8750   
h     178.0    0.361854    0.124453    0.13    0.2700    0.340    0.4375   
i     178.0    1.590899    0.572359    0.41    1.2500    1.555    1.9500   
j     178.0    5.058090    2.318286    1.28    3.2200    4.690    6.2000   
k     178.0    0.957449    0.228572    0.48    0.7825    0.965    1.1200   
l     178.0    2.611685    0.709990    1.27    1.9375    2.780    3.1700   
m     178.0  746.893258  314.907474  278.00  500.5000  673.500  985.0000   
type  178.0    1.938202    0.775035    1.00    1.0000    2.000    3.0000   

          max  
a       14.83  
b        5.80  
c        3.23  
d       30.00  
e      162.00  
f        3.88  
g        5.08  
h        0.66  
i        3.58  
j       13.00  
k        1.71  
l        4.00  
m     1680.00  
type     3.00

In [4]:
data.shape

(178, 14)

In [5]:
X = data.drop('type',axis=1)
Y = data['type']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.10)

In [8]:
X_train.head()
X_train.shape

(160, 13)

In [9]:
from sklearn.neural_network import MLPClassifier

In [10]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [11]:
mlp.fit(X_train,Y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [12]:
predictions = mlp.predict(X_test)

In [13]:
from sklearn.metrics import classification_report,confusion_matrix

In [14]:
print(confusion_matrix(Y_test,predictions))

[[7 0 0]
 [2 0 5]
 [2 0 2]]


In [15]:
print(classification_report(Y_test,predictions))

             precision    recall  f1-score   support

          1       0.64      1.00      0.78         7
          2       0.00      0.00      0.00         7
          3       0.29      0.50      0.36         4

avg / total       0.31      0.50      0.38        18



C:\Users\Palash Goyal\AppData\Roaming\Python\Python35\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
predictions

array([1, 1, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3], dtype=int64)

# With Tensorflow


In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

seed = 1234
np.random.seed(seed)
tf.set_random_seed(seed) #making result reproducible 

In [2]:
dataset = pd.read_csv('/Blog/RNN.csv')
dataset = pd.get_dummies(dataset, columns=['type']) # One Hot Encoding of selected column
values = list(dataset.columns.values)

In [3]:
y = dataset[values[-3:]]
y = np.array(y, dtype='float32')
X = dataset[values[0:-3]]
X = np.array(X, dtype='float32')

In [4]:
indices = np.random.choice(len(X), len(X), replace=False)
X_values = X[indices]
y_values = y[indices]

In [5]:
test_size = 10
X_test = X_values[-test_size:]
X_train = X_values[:-test_size]
y_test = y_values[-test_size:]
y_train = y_values[:-test_size]

In [6]:
interval = 50
epoch = 500

# Initialize placeholders
X_data = tf.placeholder(shape=[None, 13], dtype=tf.float32)
y_target = tf.placeholder(shape=[None, 3], dtype=tf.float32)

hidden_layer_nodes = 8
# Create variables for Neural Network layers
w1 = tf.Variable(tf.random_normal(shape=[13,hidden_layer_nodes])) # Inputs -> Hidden Layer
b1 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes]))   # First Bias
w2 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes,3])) # Hidden layer -> Outputs
b2 = tf.Variable(tf.random_normal(shape=[3]))   # Second Bias

hidden_output = tf.nn.relu(tf.add(tf.matmul(X_data, w1), b1))
final_output = tf.nn.softmax(tf.add(tf.matmul(hidden_output, w2), b2))

loss= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_target, logits=final_output))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.002).minimize(loss)

In [7]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print('Training the model...')
for i in range(1, (epoch + 1)):
    sess.run(optimizer, feed_dict={X_data: X_train, y_target: y_train})
    if (i % interval) == 0:
        print('Epoch', i, '|', 'Loss:', sess.run(loss, feed_dict={X_data: X_train, y_target: y_train}))

print()
for i in range(len(X_test)):
    print('Actual:', y_test[i], 'Predicted:', np.rint(sess.run(final_output, feed_dict={X_data: [X_test[i]]})))

Training the model...
Epoch 50 | Loss: 1.13257
Epoch 100 | Loss: 1.13236
Epoch 150 | Loss: 1.1318
Epoch 200 | Loss: 1.13207
Epoch 250 | Loss: 1.13152
Epoch 300 | Loss: 1.13215
Epoch 350 | Loss: 1.13198
Epoch 400 | Loss: 1.13205
Epoch 450 | Loss: 1.13037
Epoch 500 | Loss: 1.1302

Actual: [ 0.  0.  1.] Predicted: [[ 0.  0.  1.]]
Actual: [ 1.  0.  0.] Predicted: [[ 0.  0.  1.]]
Actual: [ 0.  0.  1.] Predicted: [[ 0.  0.  1.]]
Actual: [ 1.  0.  0.] Predicted: [[ 0.  0.  1.]]
Actual: [ 0.  0.  1.] Predicted: [[ 0.  0.  1.]]
Actual: [ 0.  0.  1.] Predicted: [[ 0.  1.  0.]]
Actual: [ 0.  1.  0.] Predicted: [[ 0.  0.  1.]]
Actual: [ 1.  0.  0.] Predicted: [[ 0.  0.  1.]]
Actual: [ 1.  0.  0.] Predicted: [[ 0.  0.  1.]]
Actual: [ 1.  0.  0.] Predicted: [[ 0.  0.  1.]]
